# Dependencies
markdown:         redcarpet

# Permalinks
permalink:        pretty

# Setup
title:            Sudhindra Rao
tagline:          '&beta;-release of my thoughts...'
description:      'Developer, Coach, Practitioner, Robotics Geek, Cricket Fan in San Francisco'
url:              http://betarelease.github.com

author:
  name:           'Sudhindra Rao'
  url:            https://twitter.com/sudhindraRao

excerpt_separator: <!--more-->
# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/betarelease
