# Site

name: Beta Release
title: Beta Release
locale: en_US
description: releasing my thoughts.. 1 beta at a time
logo: 'images/beta.png'
favicon: 'images/favicon.ico'
disqus: 'betareleasedraftingrandomthoughts'
share: true
comments: true

url: //betarelease.github.io

permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Site owner
owner:
  name: Sudhindra Rao
  avatar: images/grand_canyon.png
  disqus-shortname: betareleasedraftingrandomthoughts
  bio: "Hi, I am Sudhindra, I like to talk about technology and help people build software at a sustainable pace. If you like what you read here follow me on twitter."
  twitter: https://twitter.com/sudhindraRao
  github: betarelease
  linkedin: sudhindrarao

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: images/grand_canyon.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

# Paginate
paginate: 10

sass:
  sass_dir: _sass
  style: compressed

include: ["_pages", ".htaccess"]
# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
